<?
//-------------------------------- Initialization --------------------------//
$__in = array();		/**< Global array of input. */
$__out = array();		/**< Global array of output. */
$__config = array();		/**< Global array of configuration automatically generated by the configuration module and saved in uploads/configuration/config.php. */
$__errors = array();		/**< Global array of user errors. */
$__info = array();		/**< Global array of information (any success messages or warnings shown to the user). */
$__controller = NULL;		/**< Global Controller Object to be accessed from any other object. */

define("DEBUG", true);						/**< specifies whether the site is in debug mode or not if in debug mode errors are shown on the page else the errors are logged in the log file.*/
define("DB_ENGINE", "mysql");					/**< The database engine select from these (mysqk, sqlite)*/
define("HTML_ROOT", "/gen2/");						/**< the HTML root of the site set to / if the site is on the document root or set to another folder if it is on a sub folder. used by the browser to access images or style sheets on the site. */

define("PHP_ROOT", dirname(__FILE__) . "/");	/**< the PHP root of the application it is the Server document root variable + the html root (used by php to access files on the site.) */
define('SMARTY_DIR', PHP_ROOT . 'smarty/libs/');/**< The smarty directory constrant used by the smarty classes*/

define("DB_HOST", "localhost");
define("DB_USER", "root");
define("DB_PASS", "");
$__out['DEBUG'] = DEBUG;
$__out['HTML_ROOT'] = HTML_ROOT;

?>
